iterative/dvc-data

src/dvc_data/db/reference.py
src/dvc_data/objects/reference.py

Initial changes to better separate raw objects from dereferencing logic.
Fixes #29

ref: separate raw objects from dereferencing

---

.github/workflows/release.yml
.github/workflows/tests.yml
CONTRIBUTING.rst
noxfile.py
setup.cfg

Part of https://github.com/iterative/dvc/issues/7708

dvc-data: drop python 3.7

---

src/dvc_data/objects/reference.py

We used to use `pickle` because of the way `FS_CLS` was stored,
but now we use `str` for it, so we can switch to json, which is
consistent with other objects (e.g. `Tree`).

ref: use json instead of pickle

---

src/dvc_data/stage.py

Introduced in https://github.com/iterative/dvc/pull/7597

stage: use odb_ instead of odb

---

src/dvc_data/hashfile/state.py

This revisit achieves a few things:
1) ensures we are not using slow pickle by using simple types like str/bytes
2) changes format from inode-based to fs&path-based, laying the groundwork
for supporting filesystems other than localfs
3) due to much less churn (thanks to 2), changes eviction_policy from LRU to
LRS, which is much better for performance

state: revisit format

---

src/dvc_data/objects/tree.py

Discovered while trying to compile with mypyc.

tree: fix type annotations

---

src/dvc_data/hashfile/meta.py

Same as in https://github.com/iterative/dvc-data/pull/56

meta: don't use dataclass

---

src/dvc_data/hashfile/db.py
src/dvc_data/stage.py

Followup for https://github.com/iterative/dvc-data/pull/47

stage: fix external outputs

---

setup.cfg
src/dvc_data/hashfile/obj.py

Same as in https://github.com/iterative/dvc-objects/pull/63

hashfile: obj: add __slots__

---

src/dvc_data/stage.py

Better reflects what's going on these days.

stage: adjust pbar message

---

src/dvc_data/stage.py

This is closer to how objects should be built and allows us to save up some
overhead on path manipulation. E.g. `dvc status` in `dvc-bench` takes ~0.2 sec
less now (from ~4.1 down to ~3.9).
Pre-requisite to also building Tree objects along the way.

stage: use walk instead of find

---

cli.py
noxfile.py
pyproject.toml

A few more CLI commands that I was using while working on `dvc status`. :)

add few more cli options: diff/merge-tree/update-tree/checkout

---

src/dvc_data/hashfile/hash.py

Fixes https://github.com/iterative/dvc/issues/5560

hash: ensure hash_value is string

---

pyproject.toml
setup.cfg
src/dvc_data/cli.py
src/dvc_data/hashfile/hash.py

This will be useful for testing, and playing with different hashes.

hash: add blake3 to the hash registry

---

src/dvc_data/cli.py

Adds a pseudo-random tree generator. The no. of files and directories created may be slightly different.
```console
$ dvc-data gentree dataset 10000
$ dvc-data gentree dataset 10000 1Gb
$ dvc-data gentree dataset 10000 --depth 5
```

cli: add gentree

---

src/dvc_data/cli.py

du was returning size of just the hashfile, instead of the whole tree.

cli: fix du for a tree

---

src/dvc_data/cli.py

I am using `typer.echo` for `cat_object`, as `typer.echo` supports printing bytes directly to the stdout without encoding (which is basically `sys.stdout.buffer.write() + sys.stdout.buffer.flush()`).

cli: simplify, use print instead of typer.echo

---

src/dvc_data/index.py
src/dvc_data/repo.py
tests/test_index.py

Basic implementation to help us bridge the gap between dvc's Repo.index and dvc-data.

dvc_data: introduce basic data index

---

src/dvc_data/build.py
src/dvc_data/fs.py
src/dvc_data/index.py
tests/test_index.py

Basic variant of dvc's DataFileSystem, but now using index, so we could slowly migrate to it.

dvc-data: add DataFileSystem

---

src/dvc_data/fs.py
src/dvc_data/index.py

Avoids creating large lists of data index items, which saves us a lot of time
in operations like `dvc list`. E.g. with data-registry we are now down from
29sec to 2sec.

fs: avoid needlessly creating giant obj lists

---

setup.cfg
src/dvc_data/hashfile/hash.py
src/dvc_data/repo.py
tests/benchmarks/test_checkout.py
tests/hashfile/test_utils.py

deps: bump dvc-objects to 0.1.15

---

src/dvc_data/__init__.py
src/dvc_data/build.py
src/dvc_data/checkout.py
src/dvc_data/cli.py
src/dvc_data/db/index.py
src/dvc_data/fs.py
src/dvc_data/hashfile/_ignore.py
src/dvc_data/hashfile/hash.py
src/dvc_data/hashfile/istextfile.py
src/dvc_data/hashfile/obj.py
src/dvc_data/hashfile/utils.py
src/dvc_data/status.py

Also use less of `dvc_objects.fs`.

dvc_data: misc changes: fix imports and copy utils

---

src/dvc_data/index.py
tests/test_index.py

Very basic functionality to enable prototyping.

index: add basic transfer functionality

---

src/dvc_data/hashfile/hash.py
src/dvc_data/hashfile/meta.py
src/dvc_data/index.py
tests/test_index.py

Very basic experimental functionality for cloud versioning POC.

index: add basic collecting/saving logic

---

src/dvc_data/hashfile/meta.py

see https://github.com/iterative/dvc-data/pull/157/files#r963388931

meta: passthru info etag

---

src/dvc_data/hashfile/meta.py

I also changed the order in `Meta.info()` so that we don't modify the `Meta` object after creating it.
Note that we are not using it as a frozen object/immutable object here, because the `initialization` cost is too much for slotted-frozen classes compared to dict-based frozen classes in Python.

meta: simplify from_dict to avoid repetition

---

setup.cfg
src/dvc_data/index.py

will fix https://github.com/iterative/dvc/issues/8326

index: force info(refresh=True) on collect()

---

src/dvc_data/hashfile/tree.py
tests/hashfile/test_tree.py

Prerequisite for https://github.com/iterative/dvc/issues/8233.
Code probably needs some work, but wanted to take a look at this since it seems not that hard to support merge types besides add-only.

tree: add merge types

---

src/dvc_data/index.py
tests/test_index.py

Avoids overloading `save()`. `upload_odb` will also belong here, since it is a caching side-effect of computing hashes.

index: handle computing md5s separately from saving

---

src/dvc_data/hashfile/tree.py
tests/hashfile/test_tree.py

Found a small bug in https://github.com/iterative/dvc-data/pull/160

tree: fix merge error for both deleted

---

src/dvc_data/index.py
tests/test_index.py

Basic implementations for saving index in a single json and diskcache db.
This should effectively act as `state` in the near future.
Some rough timings for dvc-bench repo with all datasets (~120K entires):
```
write_db: 2.62
read_db: 1.34
write_json: 0.88
read_json: 0.85
```

index: add [read,write]_[db,json]

---

src/dvc_data/hashfile/tree.py
src/dvc_data/index.py

Allows recollecting without dropping hash_info.

index: collect: add update flag

---

src/dvc_data/index/__init__.py
src/dvc_data/index/checkout.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py
src/dvc_data/index/serialize.py

To better reflect the structure for functionality that got conceptually more or less settled.

index: change layout

---

src/dvc_data/index/index.py
tests/test_index.py

This is no longer needed (use build() instead).

index: delete unused collect()

---

src/dvc_data/index/index.py

fixes https://github.com/iterative/dvc/actions/runs/3216435563/jobs/5258323572

index: fix hash_info type assertion

---

src/dvc_data/index/__init__.py
src/dvc_data/index/add.py
src/dvc_data/index/build.py
src/dvc_data/index/checkout.py
src/dvc_data/index/diff.py
src/dvc_data/index/index.py
src/dvc_data/index/serialize.py
tests/test_index.py

Similar to what we already have in `dvc diff`.

index: diff: add basic rename detection 

---

src/dvc_data/index/diff.py

Regression from https://github.com/iterative/dvc-data/pull/212

index: diff: fix change type detection

---

src/dvc_data/index/index.py

Current .dir obj format doesn't include subdirs, so we need to create entries for them manually.
This makes indexes loaded from objects and indexes built from filesystem match.

index: load: create entries for subdirs

---

src/dvc_data/index/index.py
src/dvc_data/index/save.py
src/dvc_data/index/view.py

prereq for https://github.com/iterative/dvc/issues/8506

index: fix dir handling when saving from views

---

.pre-commit-config.yaml
pyproject.toml
src/dvc_data/hashfile/cache.py
src/dvc_data/hashfile/utils.py

See https://github.com/PyCQA/bandit.

add bandit, a security linter

---

src/dvc_data/hashfile/tree.py

prerequisite for https://github.com/iterative/dvc/issues/8293

hashfile: add tree.update_meta

---

src/dvc_data/index/build.py
src/dvc_data/index/checkout.py
src/dvc_data/index/save.py

see https://github.com/iterative/dvc/issues/8480

index: fix Meta.from_info s3 bug

---

src/dvc_data/index/view.py
tests/test_index.py

- `DataIndexView` is now lazy-loading, so view construction is cheap, and key filtering only happens on traversal/iteration. Previously it was the other way around
- View keys are no longer cached, this makes repeated iteration performance slower in views, but also means that views now always reflect changes made in the main index (previously if prefixes or keys were added/removed to the main index after the view was constructed, the view would ignore those changes)
- Views now properly load unloaded directories on `view.iteritems()` (previously we accounted for this downstream in DVC with an explicit index.load(), but that required loading the entire data index instead of only loading dirs from which are included in the view)

index: lazy load views

---

setup.cfg
src/dvc_data/hashfile/db/__init__.py
src/dvc_data/hashfile/db/reference.py
src/dvc_data/hashfile/transfer.py

see https://github.com/iterative/dvc-objects/pull/181#discussion_r1065743880

deps: bump dvc-objects to 0.14.1

---

src/dvc_data/hashfile/meta.py

Reverts part of #131
Found during work on https://github.com/iterative/dvc-data/pull/248
Kudos @skshetry for suggestions in #248

meta: don't use slower asdict

---

src/dvc_data/hashfile/meta.py

meta: remove unused _filter_default_or_none

---

src/dvc_data/index/diff.py
src/dvc_data/index/index.py
src/dvc_data/index/view.py

Introduces `shallow` flag and improves `hash_only`.
Pre-requisite for https://github.com/iterative/dvc/issues/8761

index: diff: misc improvements

---

src/dvc_data/index/save.py

index: md5: save to the legacy state

---

src/dvc_data/index/build.py

This is a very common use case in dvc, so it is useful to have a one stop shop for it and not waste time re-iterating.

index: build: support compute_hash and state flags

---

setup.cfg
src/dvc_data/hashfile/db/__init__.py
src/dvc_data/hashfile/db/reference.py
src/dvc_data/hashfile/status.py
src/dvc_data/hashfile/transfer.py
tests/hashfile/test_db.py
tests/hashfile/test_db_index.py
tests/hashfile/test_utils.py

requires https://github.com/iterative/dvc-objects/pull/180
- use batched `odb.add` in `hashfile.transfer`

use new dvc-objects batching

---

setup.cfg
src/dvc_data/index/checkout.py

related: https://github.com/iterative/dvc/issues/8774, https://github.com/iterative/dvc/issues/8837

index: use generic.status before checkout file creation

---

src/dvc_data/hashfile/meta.py

Closes https://github.com/iterative/dvc/issues/8855

`hashfile.meta`: Get `version_id` from  `generation` for `gs` protocol.

---

src/dvc_data/index/view.py
tests/test_index.py

https://github.com/iterative/dvc/pull/8866

index: view: properly handle filtered-out entries

---

src/dvc_data/hashfile/meta.py

Do review https://github.com/iterative/dvc/pull/8862, before reviewing this. :)

meta: add remote meta

---

.pre-commit-config.yaml

See https://github.com/PyCQA/isort/issues/2077

pre-commit: upgrade isort

---

src/dvc_data/index/view.py

index: view: don't forget to override odb/remote_map

---

src/dvc_data/index/diff.py
tests/index/test_diff.py

When `index.diff()` is using both meta and hash info comparison, it should only return `ADD`/`DELETE`/`UNCHANGED` when both the meta and hash info diffs return the same result. Otherwise, any mixed results should be returned as a `MODIFY`.
This also fixes a bug where `diff(meta_only=True)` would only return either `UNCHANGED` or `MODIFY`

index: fix combined meta/hashinfo diff results

---

src/dvc_data/index/save.py

related: https://github.com/iterative/dvc/issues/8932

index: fix bad assertion in index.save

---

src/dvc_data/index/checkout.py

Fixes partially https://github.com/iterative/dvc/issues/8824.

test if the filesystem supports versioning

---

src/dvc_data/hashfile/tree.py

https://github.com/iterative/dvc-data/pull/306/files#r1100907907

tree: compute old hash even when with meta

---

src/dvc_data/index/index.py

index: storage: don't forget to adjust remote_path

---

src/dvc_data/index/index.py

Related https://github.com/iterative/dvc/pull/8962

index: storage: introduce cache/remote_exists helpers

---

src/dvc_data/index/index.py

Part of https://github.com/iterative/dvc/pull/8962

index: storage: raise StorageError if missing storage

---

src/dvc_data/index/index.py

Ideally we would pass it down to the odb so it could use it internally as well, but for for now keeping at storage level to see if that's enough for https://github.com/iterative/dvc/pull/8962

index: storage: use index in ObjectStorage

---

src/dvc_data/index/view.py

This also reduces `view.ls()` performance at least 4 times in some cases, which is important for `diff` and other operations.

index: view: simplify ls filtering logic

---

src/dvc_data/fs.py

Related https://github.com/iterative/dvc/pull/9057

fs: get_file: handle dirs like fsspec's localfs

---

src/dvc_data/hashfile/build.py

hashfile: build: don't forget default value for next()

---

src/dvc_data/fs.py
src/dvc_data/index/build.py
src/dvc_data/index/index.py
tests/test_index.py

Fixes #336
Related https://github.com/iterative/dvc/issues/8789

index: load: support loading dirs from FileStorage

---

setup.cfg

To include fix: https://github.com/iterative/sqltrie/commit/cff6cdff5f9ebb59578d706df1e571f1d0583e67

deps: bump sqltrie>=0.3.1,<1

---

src/dvc_data/index/__init__.py
src/dvc_data/index/fetch.py
src/dvc_data/index/index.py
tests/test_index.py

Basic implementation that we can build upon.
Fixes #341

index: introduce basic fetch

---

src/dvc_data/index/checkout.py

Trying to achieve parity for `dvc checkout` migration in https://github.com/iterative/dvc/pull/9444

checkout: misc fixes

---

src/dvc_data/index/checkout.py

More features/fixes to make it work for `dvc checkout`.
Notable mentions:
* adds support for meta.isexec comparison, thus allowing us to chmod right in checkout instead of `output.set_exec` like we used to. This can also be extended for #274
* file creation is parallelized through `transfer`, unlike `hashfile.checkout`
Related https://github.com/iterative/dvc/pull/9444

index: checkout: more fixes

---

src/dvc_data/index/checkout.py

Needed for https://github.com/iterative/dvc/pull/9444

index: checkout: temporarily support state

---

src/dvc_data/index/diff.py

Related https://github.com/iterative/dvc/pull/9444

index: diff: make shallow look at hash_info

---

src/dvc_data/index/index.py

Related https://github.com/iterative/dvc/pull/9444

index: load: don't try to load objects from file storage

---

src/dvc_data/index/diff.py

Found during https://github.com/iterative/dvc/pull/9424

index: diff: take entry_diff into account

---

src/dvc_data/hashfile/transfer.py
src/dvc_data/index/checkout.py
src/dvc_data/index/fetch.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py
tests/index/conftest.py

Related https://github.com/iterative/dvc/pull/9424

index: fetch: handle object transfer

---

setup.cfg
src/dvc_data/index/index.py
src/dvc_data/index/view.py

Needed for https://github.com/iterative/dvc/pull/9424

index: introduce delete_node

---

src/dvc_data/index/checkout.py
src/dvc_data/index/diff.py

Users won't perceive dvc as hanging during checkout anymore.

index: checkout: use progress bar for diff stage

---

src/dvc_data/index/fetch.py

Related https://github.com/iterative/dvc/pull/9579

index: fetch: don't update meta on checkout

---

src/dvc_data/index/index.py
tests/index/test_index.py

Leftover from past migration steps.

index: don't assume .dir hash means a directory

---

src/dvc_data/index/fetch.py

To make sure the view we create sees the subsequent changes.

index: fetch: create views after building the index 

---

src/dvc_data/index/fetch.py
src/dvc_data/index/save.py

This won't work with sqlite-based trie.
Related https://github.com/iterative/dvc/pull/9579

index: md5: don't modify index we are iterating

---

src/dvc_data/index/fetch.py

Related https://github.com/iterative/dvc/pull/9579

index: fetch: don't use entry.loaded

---

src/dvc_data/hashfile/tree.py
src/dvc_data/index/build.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py

related: https://github.com/iterative/dvc/issues/9580

index: support setting computed entry hash name in build/save

---

src/dvc_data/index/checkout.py
src/dvc_data/index/index.py

Related https://github.com/iterative/dvc/issues/9584

index: checkout/fetch: fix cloud versioning

---

src/dvc_data/index/build.py
tests/index/test_build.py
tests/index/test_index.py

Pre-requisite for https://github.com/iterative/dvc/issues/9541

index: make build_entry raise on FileNotFound

---

src/dvc_data/index/__init__.py
src/dvc_data/index/fetch.py
tests/index/test_index.py

Similar to https://github.com/iterative/dvc-data/pull/390 and https://github.com/iterative/dvc-data/pull/389

index: fetch: split into collect and fetch

---

src/dvc_data/index/checkout.py

This gives better control to the user.

checkout: apply: use onerror instead of allow_missing

---

src/dvc_data/index/checkout.py

These clearly don't belong in the library and should be handled by the user.
Related https://github.com/iterative/dvc/issues/9618

index: checkout: don't accept prompt/force arguments

---

src/dvc_data/index/checkout.py
src/dvc_data/index/fetch.py

User already has it from `compare` result.
Related iterative/dvc#9618

index: checkout: apply: don't return diff.changes

---

src/dvc_data/index/fetch.py

related: https://github.com/iterative/dvc/issues/9226

index: clear hash info for files with missing version ID on fetch

---

src/dvc_data/index/fetch.py

see https://github.com/iterative/dvc-data/pull/399#discussion_r1244933646

fetch: clarify behavior when collecting files w/missing version ID

---

src/dvc_data/fs.py

Related iterative/dvc#9462 iterative/dvc#9512

fs: get_file: fallback to fs.get_file if transfer didn't work

---

src/dvc_data/cli.py
src/dvc_data/hashfile/build.py

The callback coverage hasn't been very good in the `build` to begin with, this is just trying to replace an existing one and nothing more.

hashfile: build: remove implicit Tqdm progress bar

---

src/dvc_data/hashfile/build.py

build: use relative_update() instead of update()

---

src/dvc_data/index/collect.py
src/dvc_data/index/fetch.py
tests/index/test_index.py

Collect functionality is going to be useful for push/gc/etc in the next PRs.

fetch: tweak collect

---

src/dvc_data/fs.py
tests/index/test_index.py

Prerequisite for https://github.com/iterative/dvc/issues/9745

ls: raise NotADirectory if path is not a directory

---

src/dvc_data/fs.py

Leftover from https://github.com/iterative/dvc-data/pull/407

fs: ls: catch KeyError

---

src/dvc_data/index/push.py
tests/index/test_index.py

Very basic implementation to start with. Will be tweaked later.
Pre-requisite for https://github.com/iterative/dvc/issues/9333

index: introduce basic push

---

src/dvc_data/hashfile/transfer.py

related: https://github.com/iterative/dvc/issues/9666

hashfile: drop implicit tqdm callback from transfer()

---

src/dvc_data/index/view.py

index: view: don't forget onerror

---

src/dvc_data/index/index.py

Leftover from https://github.com/iterative/dvc-data/pull/417 🤦

index: load: don't mark dir as loaded on DataIndexDirError

---

setup.cfg
src/dvc_data/index/checkout.py

Related https://github.com/iterative/dvc/issues/9733

index: checkout: use onerror for broken dirs

---

src/dvc_data/fs.py

Teaches `DataFileSystem` to cache streams to appropriate odb when `cache=True`.
Now that we have two odb locally makes it impossible to pass `cache_odb`, so we need to make `DataFileSystem` itself smarter.
My goal here is to keep compatibility with 2.x versions, so I haven't added cloud versioning support yet. 
Also, the following is a nice interface that we should support in `DvcFileSystem`.
```python
with fs.open(..., cache=True) as f:
pass
```
See dvc changes: iterative/dvc#9849

datafs: support caching files when cache=True kwarg is passed

---

src/dvc_data/fs.py

On `fs.get_file(..., cache=True)`, it'll download to cache odb, and then link according to appropriate `cache_types`.
Note that the `_upload_file` interface that it goes through may be slower, but this will only happen when `cache=True`. The normal calls still go direct to underlying `fs` so it's faster.
With this change, all operations that involve downloading files support `cache=True`, eg: `get/get_file/open/cat_file/cat`.

fs.get_file: support cache=True in datafilesystem

---

src/dvc_data/hashfile/db/migrate.py

Fixes #437 
I've tested that this fixes the issue I hit when I discovered this as well as the MWE I posted in the issue. Not sure how to write a test for this in this repo without relying on the larger DVC module, but this is also a simple enough fix and I'm not sure if migrate has tests in here anyway.

Fix empty migrate

---

src/dvc_data/index/push.py

Note that this is under development and is not used yet.
Related https://github.com/iterative/dvc/pull/9807

index: push: fix transfer arguments

---

pyproject.toml
src/dvc_data/hashfile/gc.py

related: https://github.com/iterative/dvc/issues/9953

gc: filter used hash_infos by hash name

---

src/dvc_data/index/diff.py

Followup for #444
Related https://github.com/iterative/dvc/issues/9507

index: diff: support passing multiple roots

---

src/dvc_data/index/index.py

index: introduce DataIndexEntry.isdir

---

setup.cfg

To ensure people are getting a fix related to https://github.com/iterative/dvc/issues/9826

deps: bump sqltrie to >=0.8.0

---

src/dvc_data/index/collect.py

Related https://github.com/iterative/dvc/pull/9807

index: collect: keep meta/hash_info on push

---

src/dvc_data/index/index.py

Related https://github.com/iterative/dvc/pull/9807

index: storage: differentiate between key and prefix

---

src/dvc_data/index/checkout.py
src/dvc_data/index/push.py

More parity changes with old functionality
Related #456

push: test versioning and ignore missing

---

pyproject.toml

pyproject: fix typo

---

pyproject.toml

pyproject: fix entry point name

---

src/dvc_data/fs.py

Leftover from https://github.com/iterative/dvc-data/pull/479

fs: normpath: use posixpath.normapth

---

pyproject.toml
src/dvc_data/index/index.py
tests/index/test_index.py

Related https://github.com/iterative/dvc/pull/10188

index: don't forget to reset _cache on close

---

src/dvc_data/index/push.py

Related https://github.com/iterative/dvc/pull/10188
For the record, there is a higher level test in dvc for now, but I do plan on adding a bit more in dvc-data once ready.

index: push: use diff.files_create for total transferred

---

src/dvc_data/index/fetch.py

Related https://github.com/iterative/dvc/issues/10173

index: fetch: fix stats reports for FileStorage

---

src/dvc_data/index/view.py

On top of #510.
We have a `index`, which is a collection of tracked paths, and `view` which provides a filtered view over a `index`. This `view` is used on granular push/pull and other operations.
Ths PR changes the `view.ls()` API. Before, we were listing the path from the index, with `detail=True` which calls the underlying filesystem with `fs.info()` to get the metadata. Then, we were filtering path after the fact we initialized the filesystem and called `fs.info()`.
This PR changes it to list the paths first, then filters it and only then fetch the metadata information.
I might need to do some cleanups here (and add a test on `dvc` side), but it would be nice to get a confirmation that this fixes the https://github.com/iterative/dvc/issues/10309.

view.ls: filter out path before trying to get metadata information

---

src/dvc_data/index/build.py
src/dvc_data/index/checkout.py

Giving the same treatment as we do in hashfile.build.
Drops `dvc checkout MNIST/` from 12s to under 5s on my machine.
Closes https://github.com/iterative/dvc/issues/10491.

index/checkout: hash file concurrently and save state in batches
