src/dvc_data/stage.py

Temporarily re-introduce this bug for performance reasons. The proper fix is coming soon.
https://github.com/iterative/dvc-data/commit/4b4c034a0457bc5601d2a1bbb1ecbc17aace0405

stage: revert raw dir bugfix

---

src/dvc_data/hashfile/hash_info.py

We are creating lots of these instances and dataclass is significantly slower.
For example, running:
```
from dvc_data.hashfile.hash_info import HashInfo
hashes = []
for value in range(10000000):
hashes.append(HashInfo("md5", value))
```
before this PR takes ~6.1sec and after ~4.9sec.
Most of the improvement is actually coming from using `__slots__`, which were finally supported by dataclasses in 3.10.
Another (temporary) downside to using dataclass is that it is kinda buggy with other tools. E.g. `mypyc` is failing to compile it throwing an error like https://github.com/mypyc/mypyc/issues/921 for the `HashInfo.name`.

hash_info: don't use dataclass

---

src/dvc_data/diff.py

Same as https://github.com/iterative/dvc-data/pull/56

tree: don't use dataclass for numerous TreeEntry and Change

---

src/dvc_data/diff.py
src/dvc_data/objects/tree.py

This method is quite contraversial in itself, but lets for now just rename
it so it is out of the way.

tree: rename get -> get_obj

---

src/dvc_data/diff.py
src/dvc_data/objects/tree.py

Avoids creating unnecessary intermediate objects.

diff: use tree.get instead of tree.get_obj

---

cli.py
setup.cfg
src/dvc_data/hashfile/hash.py

This PR introduces several plumbing CLI commands for dvc-data.
1. `fsck`: Checks all of the objects in the database, similar to `git fsck`.
3. `ls`: List all items of the tree, similar to `git ls-tree`.
4. `stage`: Stage, and optionally write objects to database with `--write/-w`. Can write in shallow mode with `--shallow`.
5. `cat`: Print contents of the object to the terminal (and optionally verify object with `--check/-c`.
6. `p2o`/`o2p` -> Path to oid and Oid to path.
7. `genrand` -> Generate file with random content (eg: `./cli.py genrand sample.txt 1GB`).
8. `gensparse` -> Create sparse file in a portable way (eg: `./cli.py gensparse sample.txt 1GB`).
9. `hash` -> Compute hashes of file, in `--text` (dos2unix) vs `--binary` mode, with different hashing algorithms specified via …

cli for plumbing commands

---

cli.py
src/dvc_data/build.py
src/dvc_data/checkout.py

This better reflects what's going on and avoids confusion with pipeline stages.

dvc-data: rename stage -> build

---

src/dvc_data/_progress.py
src/dvc_data/hashfile/hash.py

---
- fixes https://github.com/iterative/dvc/issues/7896
- closes https://github.com/iterative/dvc-objects/pull/92
- closes https://github.com/tqdm/tqdm/pull/1341
/CC @sjawhar

fix logging filenames

---

noxfile.py
pyproject.toml
setup.cfg
src/dvc_data/__main__.py
src/dvc_data/cli.py
src/dvc_data/repo.py

We need to introduce repo concept so that the plumbing CLI command
is compatible with `dvc init` created repositories.
CLi command will try to discover `.dvc` directory. You can alternatively specify `DVC_DIR` envvar in which case it'll consider your current working directory as root and will use `DVC_DIR` as an object_dir and tmp directory for state. 
This change makes it compatible with dvc-created repositories.

introduce repo concept, make plumbing CLI available as dvc-data command

---

src/dvc_data/cli.py
src/dvc_data/objects/tree.py

The cached_property, `Tree._trie` should be invalidated in a couple of places, but it's referenced as `trie` instead of `_trie`, so it doesn't get removed. For example, we can run this:
```python
from dvc_data.objects.tree import Tree
obj = Tree()
obj._trie
obj.add(('a',), None, 'a')
print(len(obj), len(obj._trie))
```
Currently, we get:
```
1 0
```
After this fix, we correctly get:
```
1 1
```
For an alternative where the trie is actually updated instead of removed, see: https://github.com/iterative/dvc-data/pull/102

tree: fix incorrect trie attr to be _trie

---

src/dvc_data/checkout.py

local_odb.makedirs will try to chmod, which is only required
while adding to odb. We should be using to_fs.makedirs while
checking files out.
Following the discussion in https://iterativeai.slack.com/archives/CB41NAL8H/p1659605519798349?thread_ts=1659537458.508189&cid=CB41NAL8H.

checkout: use to_fs.makedirs instead of odb.makedirs

---

src/dvc_data/cli.py

Fixed `patch_file` which is expected to be a `Path` object but `click` returns a string, so it fails when trying to use the `parent` method later.
Also when modifying the path for each `appl` in the patch list there was an error while indexing the list because a string was being used instead of an integer index.

Issue with patch_file path in process_patch function

---

setup.cfg
src/dvc_data/hashfile/hash_info.py

It is like `dataclasses`, and can generate slotted classes. Regarding performance, it generates class and is out of the picture when we call it. If you look into the code it generates for `__init__`, it will be identical.
```pycon
>>> from dvc_data.hashfile.hash_info import HashInfo
>>> import inspect
>>> print(inspect.getsource(HashInfo.__init__))
def __init__(self, name=attr_dict['name'].default, value=attr_dict['value'].default, obj_name=attr_dict['obj_name'].default):
self.name = name
self.value = value
self.obj_name = obj_name
```
Just generating a repr is going to be ugly and tiresome. Example of what an actual implementation would look like (which is now generated for free for us):
```python
def __repr__(self) -> str:
return f'{self.__class__.__qualname__}(name={self.name!r}, …
```

hash_info: use attrs slotted class

---

src/dvc_data/hashfile/meta.py

This is a micro-optimization that avoids unneccessary codepaths.
The Meta class is simple class, without having nested instances, so we don't really need `recurse`. The performance improves by 2x, but this is not where we really care about it though.
It's just something I noticed and should have been set as that when I changed this class to use `attrs`.

meta: use recurse=False in attrs.asdict

---

.github/workflows/benchmark.yml
.github/workflows/tests.yml

When using previous concurrency method, whenever a release was made, running workflows for the sha in the main branch would cancel. This is not what we want, we want to only have one running workflow in a pull request but we don't want any limits on `release`/`main` branch.
Still, until further testing, I am hesitant to upstream this into py-template. Let's test this for a week.

ci: simpler concurrency

---

src/dvc_data/checkout.py
src/dvc_data/diff.py

Also fixed the checkout to use that flag so that not-in-cache and cache corrupted
are raised  properly.

diff: do not consider not-in-cache as modified

---

src/dvc_data/index.py
tests/test_index.py

For example, think of our `dvc import`s, where `entry.odb` is that repo's
remote, but `cache` is your local repo's cache.

index: separate entry odb and entry cache

---

src/dvc_data/fs.py
src/dvc_data/index.py
tests/test_index.py

This will allow `dvc ls` to use index.info() directly, which should improve performance. `DataFileSystem.ls(..., detail=True)` should also become faster.

Add index.info() and use it in fs.info() and fs.ls()

---

src/dvc_data/hashfile/meta.py

md5 is sometimes provided as a metadata (e.g. in dvcfs).

meta: add md5

---

src/dvc_data/hashfile/meta.py

This is now a bit faster than the custom `from_dict` that we had before (even before https://github.com/iterative/dvc-data/pull/169), as we don't need to call `d.get()` function too many times.
When the dictionary is empty, I see the following results:
```console
Mean +- std dev: [main] 808 ns +- 29 ns -> [s] 581 ns +- 15 ns: 1.39x faster
```
When the dictionary is non-empty, the result is small but positive:
```console
Mean +- std dev: [main2] 862 ns +- 31 ns -> [s2] 837 ns +- 25 ns: 1.03x faster
```

Meta.from_dict: micro optimization

---

src/dvc_data/index.py

Reducing to a pure and simple implementation that is easy to add progress bars to. Note that this is currently only used for cloud versioning, where state wasn't working anyway, so this won't change anything for now.
State loading/dumping should be performed on the whole index anyway.

index: md5: don't use state or LargeFileCallback

---

src/dvc_data/index/checkout.py
src/dvc_data/index/diff.py
tests/test_index.py

We are not handling dirs well during collection right now, so there are some shortcuts in this implementation among other things.

checkout: basic implementation without object checkout

---

src/dvc_data/index/checkout.py

Since checkout created new files and knows that they have particular hash, it should also update the meta. This is similar to how we do `state.save` in `hashfile.checkout`.

index: checkout: update meta along the way

---

src/dvc_data/hashfile/meta.py
tests/test_index.py

Needed for localfs scenarios. Note that we are not loading or dumping from/to dict, so this won't leak into dvcfiles.

meta: capture inode/mtime

---

src/dvc_data/hashfile/tree.py
src/dvc_data/index/__init__.py
src/dvc_data/index/checkout.py
src/dvc_data/index/diff.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py
src/dvc_data/index/view.py
tests/test_index.py

Provides read-only view into DataIndex using a filtered set of keys. Does not modify or create a new trie, only wraps the existing `index._trie` object
Should be usable in any existing dvc-data functions that don't write back to the index (i.e. save, checkout, dvcfs methods, etc)
Implements
- `iteritems`
- `traverse`
- `ls`

index: add dvc_data.index.view() and DataIndexView

---

src/dvc_data/index/build.py

This is useful when trying to modify existing index (e.g. `dvc add`, including future 
`virtual directory` operations)

index: build: introduce build_entry() and build_entries()

---

src/dvc_data/index/__init__.py
src/dvc_data/index/add.py
tests/test_index.py

Building entries from file/directory and adding them at a specific key. Similar to `dvc add`, but without hashing. Allows us to virtually add files/directories to the index, without having to have everything locally.

index: introduce basic add()

---

setup.cfg
src/dvc_data/hashfile/checkout.py
src/dvc_data/index/checkout.py
src/dvc_data/index/save.py

- `index.checkout()` will first try to transfer from odb and then fall back to entry source if it is available
- Also unifies progress behavior between `hashfile.checkout()` and `index.checkout()`
This PR does not implement batching transfer operations by filesystem (will be done in a follow up). What we will need for that is a generic version version of `fs.get()`:
https://github.com/iterative/dvc-objects/blob/d28bbccc23fa8822ca2a01374bf11ff7362784a7/src/dvc_objects/fs/base.py#L447
(`fs.get()` is currently hard coded to only work when the dest is localfilesystem, but we can do the same thing with any filesystem)

index: support checkout from entry source

---

src/dvc_data/index/checkout.py

If we are updating `entry.meta` on checkout we also need to update `entry.fs` and `entry.path`, otherwise we cannot validate metadata using `entry.meta == Meta.from_info(entry.fs.info(entry.path))`

index: update entry fs/path on checkout

---

src/dvc_data/hashfile/transfer.py

The dvc-data `transfer` implementations return integer counts due to legacy dvc push/fetch behavior reasons. We have the more detailed set data already and should just be returning that (and calling `len()` in dvc when needed for dvc UI purposes). This lets us handle fallback behavior in DVC (where we can potentially get objects that failed to transfer from an alternate source)

hashfile: return oid sets instead of success/failed counts in transfer

---

src/dvc_data/hashfile/db/__init__.py
src/dvc_data/hashfile/tree.py
src/dvc_data/index/save.py

For now keeping it in `save.py`, which is a better place than `hashfile`, but this probably will move to serialization in the future.

index: save: introduce build_tree

---

src/dvc_data/index/diff.py
src/dvc_data/index/update.py
tests/test_index.py

We don't always want unchanged entries, so we can save up on creating a lot of redundant objects in those cases.

index: diff: add with_unchanged

---

src/dvc_data/index/diff.py

Useful when metadata might be outdated or irrelevant.

index: diff: add hash_only

---

src/dvc_data/index/index.py
tests/test_index.py

Relying on `meta` is more correct as `hash_info` containing `isdir` is an implementation detail that will not stick around forever. This also allows us to handle temporary directories that we create when loading tree object or when building a new index.

index: info: use entry.meta

---

src/dvc_data/hashfile/build.py

The string manipulation used as alternative to `relparts` didn't handle the case of `path` containing a trailing fs.sep, creating a `rel_key` with the first letter missing.
Fixes https://github.com/iterative/dvc/issues/8572

_build_tree: Fix rel_key for path with trailing fs.sep.

---

src/dvc_data/index/checkout.py
src/dvc_data/index/diff.py

- Adds `index.diff(meta_cmp_key=...)` parameter
- Can be used to specify a key function which will be used to compare `old.meta` and `new.meta` (rather than comparing the entire meta instance)
- Works the same way as python `sorted(key=...)`, i.e. `meta_cmp_key=lambda m: m.etag` can be used to only compare `old.etag == new.etag` in diff
- When either or both old/new `entry.meta` is none, `meta_cmp_key` will be ignored
- additional kwargs for `index.checkout()` will be passed into `diff()` (only used when `old` index is also passed into `checkout`)
In DVC we want to avoid pushing a new version when the old and new checksums match, even if the version_ids do not match. i.e. someone else may have pushed a new version_id, but if their etag matches ours we do not need to push another duplicate …

Index: support custom meta comparison function in diff

---

src/dvc_data/index/checkout.py

Updating meta by default usually makes sense because in most cases we will checkout to the same filesystem as our "new" `index`, but this is not always the case. For worktree `update`, the "new" index is the remote's, and "old" index is local, and we checkout to local, so we do not want to update meta (which would make us lose the latest/new version ID+etag and replace them with local inode/mtime)

index: add flag for updating meta on checkout

---

src/dvc_data/index/checkout.py
src/dvc_data/index/save.py
tests/test_index.py

Related: https://github.com/iterative/dvc/issues/8359
@dberenbaum It looks like the main performance issue was that remote file transfers weren't being parallelized/batched properly for versioned remotes. Can you test with this PR and confirm that it resolves the performance issues you were seeing? Just note that `--jobs` won't be respected properly w/this PR (it will always just use the cpu core # based default). Fixing `--jobs` will need an additional change in downstream dvc once the dvc-data changes get released.
I'd prefer to not add more usage of `ThreadPoolExecutor` and am going to look into doing a proper asyncio based implementation instead, but we could consider merging this in the meantime.

index: parallelize checkout/save

---

src/dvc_data/index/save.py

Temporary connector before persistent index #208 is fully supported.
Pre-requisite for https://github.com/iterative/dvc/issues/8761

index: md5: accept legacy state

---

setup.cfg
src/dvc_data/index/index.py
src/dvc_data/index/serialize.py
src/dvc_data/index/view.py

This patch, makes us use sqltrie wrapper for pygtrie when working in memory to achive the parity with the old behavior, but also adds an `open` method that will need to be explicitly utilized by `dvc` to actually start using a persistent sqlite-based index.
Fixes #208

index: use sqltrie

---

setup.cfg
src/dvc_data/hashfile/gc.py

Use "bulk" remove in filesystems that support it.
Requires https://github.com/iterative/dvc-objects/pull/176 to don't break in localfs
Closes https://github.com/iterative/dvc/issues/5961

gc: Pass list of paths to `fs.remove`.

---

src/dvc_data/index/diff.py

This state is occuring when we are comparing two indexes and one of those knows that there is a directory with a specific hash, but can't load the info about it (e.g. cache file is missing), which means that `diff` doesn't have enough info to figure out what's changed and it looks like added/deleted entries.
This state was introduced in `dvc data status` last year and is already used by vscode.
This PR is putting it into index diff terms so we can reuse it in other places (e.g. `dvc diff`).
Pre-requisite to migrating `dvc data status` to `DataIndex` and https://github.com/iterative/dvc/issues/8761
Fixes index side of #83

index: diff: introduce with_unknown flag

---

setup.cfg
src/dvc_data/index/checkout.py
src/dvc_data/index/view.py

- force dir load on `view.ls()` (used in new diff behavior)
- use batched `fs.info` when possible in checkout
Will fix https://github.com/iterative/dvc/issues/8852

index: fix checkout with views

---

src/dvc_data/index/diff.py
tests/index/test_diff.py
tests/test_index.py

Previously if one index had a file without hash and second had no file at all diff would say that this file was added/deleted in `hash_only=True` mode, which is incorrect.
See https://github.com/iterative/dvc/pull/8878#discussion_r1086346424

index: diff: handle missing hash in hash_only mode

---

src/dvc_data/index/diff.py

This allows us to be much more efficient with indexes that contain tree objects by short circuiting traversal.

index: diff: skip traversing dirs with the same hash

---

src/dvc_data/index/checkout.py

When diffing with meta only (and ignoring hash info) it's possible to get a `MODIFY` change w/`None` value in old/new

index: ignore None diff entries on checkout

---

src/dvc_data/fs.py
src/dvc_data/index/checkout.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py
tests/test_index.py

Removes unserializable HashFileDB objects from DataIndexEntry, so we can reload index from persistent storage and still be able to use it where we need it.
Fixes #287

index: replace entry.odb/cache/remote with index.odb/remote_map

---

src/dvc_data/fs.py
src/dvc_data/index/add.py
src/dvc_data/index/build.py
src/dvc_data/index/checkout.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py
src/dvc_data/index/view.py
tests/test_index.py

This replaces `odb_map` and `remote_map` in `DataIndex`, and `fs` and `path` in `DataIndexEntry` incorporating everything into `Storage`, which describes where to get the data contents from no matter how they are stored (just as plain backup in a directory or in an object storage).
`DataIndexEntry.fs/path` were very confusing, as it was not clear what they really represent and were often unecessarily used during different operations (for example `checkout` that mutates those instead of returning a new local index). This also removes unserializable `fs` instance from `DataIndexEntry`, making it much easier to work with after loading.
The new `Storage.fs/path` concepts fit nicely into dvc's import functionality, by giving a clear way to declare where to get the data from.
Related …

index: introduce storage_map

---

src/dvc_data/index/checkout.py
src/dvc_data/index/index.py
src/dvc_data/index/view.py

Ideally checkout shouldn't alter existing index, but rather return a new one instead. But this is something that we currently depend on, so I want to keep it working and change this behaviour later on.

index: checkout: correctly modify index in place

---

src/dvc_data/fs.py
src/dvc_data/index/checkout.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py
tests/benchmarks/test_index.py
tests/test_index.py

Similar to already removed fs/path/odb/remote, this just doesn't belong here
and should be handled through `storage.odb`/`entry.hash_info` combo.
This marks the last unserializable field in DataIndexEntry 🎉 
Related to https://github.com/iterative/dvc/pull/8827

index: get rid of DataIndexEntry.obj

---

src/dvc_data/index/checkout.py

Checkout wants to be able to use links most of the time, so there is really no reason to use in-memory odb for now.
Leftover from https://github.com/iterative/dvc-data/pull/304
Required for https://github.com/iterative/dvc/pull/8989

index: checkout: don't use storage.odb

---

src/dvc_data/hashfile/tree.py
src/dvc_data/index/index.py

The tree objects that we build for cloud versioning have to have meta in them, so we have to be able to load our index using those objects.
Required for https://github.com/iterative/dvc/pull/8989

index: support loading from Tree objects serialized with meta

---

src/dvc_data/index/view.py

Oversight from https://github.com/iterative/dvc-data/pull/303

index: view: remove redundant tree.get during iteritems

---

src/dvc_data/index/index.py

We have `storage.remote` already, which is an odb, but we need an equivalent for cloud versioning.
Related https://github.com/iterative/dvc/pull/8962

index: introduce storage.remote_fs/path

---

src/dvc_data/fs.py
src/dvc_data/index/add.py
src/dvc_data/index/build.py
src/dvc_data/index/checkout.py
src/dvc_data/index/index.py
src/dvc_data/index/save.py
tests/test_index.py

This does a few things:
1) partitions storage into 3 categories:
* `data` - immediately accessible data contents (e.g. right in your workspace)
* `cache` - data contents stashed somewhere aside
* `remote` - data contents stoshed remotely (kinda like cold cache)
2) makes so that each storage can be either object-based (our typical odbs) or
filesystem-based (e.g. cloud versioning or just a plain old backup copy).
3) settles `save` convention as being a transfer of data contents from `data`
storage (e.g. workspace) to `cache` storage. But also allows to pick other
storage type to get the data from (e.g. `remote`, which is how we use it
for cloud-versioning)
4) settles `checkout` convention as being a transfer of data contents from `cache`,
but also allows one to pick other storage type to …

index: settle storage layout/operations

---

src/dvc_data/index/checkout.py

Not the best flag name. Just trying to comply with the old behaviour.

index: checkout: don't update storage if update_meta is False

---

setup.cfg

Should simplify conda releases and allows bumping dvc-objects without requiring bumped dvc-data release
- Unpins `dvc-objects` and `sqltrie` versions (with capped major ver)
related: https://github.com/iterative/dvc/pull/9056

deps: use version ranges for subpackages

---

src/dvc_data/fs.py

Related to https://github.com/iterative/dvc/issues/9030.
Used in https://github.com/iterative/dvc/pull/9183.

datafs: allow caching remote streams to odb

---

src/dvc_data/fs.py
src/dvc_data/hashfile/build.py

This happens when a directory exists (e.g. os.lexists() is True) but any attempt at looking into it results in `FileNotFoundError` because either the symlink is broken or, in datafs, we don't have the info about the dir which results in `TreeError` which is equivalent to a broken symlink.
Found these while working on https://github.com/iterative/dvc/issues/8789

hashfile: build: handle broken symlink or TreeError

---

src/dvc_data/hashfile/meta.py
src/dvc_data/index/index.py
tests/index/test_diff.py
tests/test_index.py

Happens when we've backed out our data to data storage but we are not sure if it is a directory or a file.
Related https://github.com/iterative/dvc/issues/8789

index: try loading missing meta from file storage

---

src/dvc_data/index/index.py

These are leftovers from early experiments.

index: remove unused transfer/push/fetch/commit

---

src/dvc_data/hashfile/tree.py

Related to https://github.com/iterative/dvc/issues/4657.
Using it in https://github.com/iterative/dvc/pull/9389/files to prune subtree and add items to the trie and rebuild tree out of it.

hashfile.tree: add as_trie/from_trie

---

src/dvc_data/cli.py

Disable cache check by default as it is extremely slow. Also disable hash check for each file during diff by default.
I went with monkeypatching in CLI as I was not sure if there was interest in supporting this in ODB.

cli: diff: disable cache check by default

---

src/dvc_data/index/index.py

Related #341
Related https://github.com/iterative/dvc/pull/9424

index: make sure storage exists

---

src/dvc_data/fs.py

Still not 100% sold on this approach, but it does make some sense.
Required for https://github.com/iterative/dvc/issues/9385

fs: get_file: try linking from storage

---

src/dvc_data/fs.py
src/dvc_data/index/index.py

These are legacy things that are very fragile and confusing. The definition of both is very murky, but it is clear that both just don't belong in dvc-data.
Run into these while working on https://github.com/iterative/dvc/pull/9444 where they broke.

fs: get rid of isout/isdvc

---

src/dvc_data/index/fetch.py
src/dvc_data/index/index.py

`dvc fetch` noop in `dvc-bench` goes from ~30sec down to ~10sec for me.
Next step is to also cache remote index, so we don't have to waste those ~10sec checking files in the remote.
Fixes #375

index: fetch: cache collected files

---

src/dvc_data/index/fetch.py

This avoids reloading the index when used later on.
Related https://github.com/iterative/dvc/pull/9579

index: fetch: use entry.loaded when collecting fs_index

---

src/dvc_data/index/index.py

This is the last place where we've been using it.
Comes with a significant reduction in object size (600 vs 88 bytes as measured by pympler.asizeof), which should make us faster and eat up less memory.

index: use attrs instead of dataclass

---

src/dvc_data/index/__init__.py
src/dvc_data/index/checkout.py
src/dvc_data/index/fetch.py
tests/index/test_checkout.py
tests/index/test_index.py

checkout is an overloaded term that does too much in our case (just look at the number of arguments we pass to it). We have clear separate stages within it these days and so can split it up to be less overloaded and easier to use when need to indicate progress to users.
The flag separation is not the cleanest right now and will need some work in the near future (e.g. why not check cache during `compare` stage to know what we can delete and not wait until trying to `apply` changes), but it is still an improvement as is.
Per https://github.com/iterative/dvc-data/pull/373#discussion_r1225675804 and similar to https://github.com/iterative/dvc-data/pull/389

index: checkout: split into compare and apply

---

src/dvc_data/index/checkout.py

We already find parents during diff and create them as a separate step.

index: checkout: don't try to create parent dirs twice

---

src/dvc_data/hashfile/transfer.py

In the middle of a rather large `dvc push` I noticed that dvc seemed to be hanging, it wasn't, but it also wasn't producing any output for hours. After some debugging I found that the slow bit of code is in the `_add`, and I added a tracing statement above it so if the user runs with `-vv` they can at least see that DVC is indeed doing something.

Add trace to transfer code

---

src/dvc_data/index/index.py

Reverts iterative/dvc-data#409
Will introduce a proper `onerror` mechanism instead.
Fixes https://github.com/iterative/dvc/issues/9785

Revert "index: load: ignore misc exceptions"

---

src/dvc_data/fs.py
src/dvc_data/index/diff.py
src/dvc_data/index/index.py
tests/index/test_index.py

Also fixes legacy TreeError/DataIndexError mess and doesn't mark directories that we've failed to load as loaded in cache, preventing cache corruption.
Kudos @dberenbaum for investigation.
Note that behaviour in https://github.com/iterative/dvc/issues/9785 is not fixed by this, because it is more related to how we treat this error in datafs, dvcfs and also how fsspec's `fs.walk()` ignores broken directories. So we will look into maybe raising `DataIndexDirError` instead of treating it as a broken directory and ignoring in `datafs/dvcfs.ls`.
Fixes #413
Related https://github.com/iterative/dvc/issues/9785
Related https://github.com/iterative/studio/pull/6541

index: introduce basic onerror

---

src/dvc_data/fs.py
tests/index/test_index.py

So far there doesn't seem to be a need to ignore this error in fs related code, so just passing it through without a way to configure it through `ls`.
Will need a corresponding fix on dvc's side in a separate PR. We will need to ignore it in index-related stuff like `dvc fetch`.
Related https://github.com/iterative/dvc/issues/9785

datafs: ls: pass DataIndexDirError through

---

src/dvc_data/index/fetch.py

Just a dirty trick to make sure we don't have any weird auth errors that will get in the way later on.
Ideally we should wrap the whole fetching logic and do as much as we can and only then raise, but this might resolve 99% potential problems for now. We can revisit this later.
Related https://github.com/iterative/studio/pull/6541

index: fetch: check connection before downloading

---

src/dvc_data/index/checkout.py
src/dvc_data/index/diff.py
tests/index/test_checkout.py

If some directory is missing its cache and we can't restore it, we should just not create it at all instead of trying to create an empty directory.
Related https://github.com/iterative/dvc/issues/9733

index: checkout: don't create broken directories

---

src/dvc_data/index/checkout.py

Currently you might run into `ERROR: unexpected error - list.remove(x): x not in list` if you are trying to checkout a broken dir (no access to .dir) when there is an old empty dir that already exists.

index: checkout: handle possibly existing dirs with broken new dirs

---

src/dvc_data/index/collect.py

Only dvcfs implements fsid right now, but we'll be gradually adding it to other filesystems. Though important to note that for most other filesystems, the path contains some unique things like bucket name, which provide enough uniqueness in most cases.
Fixes iterative/dvc#9904

index: collect: use fsid if available

---

src/dvc_data/hashfile/gc.py

Prerequisites to make gc more user friendly by exposing a dry option and returning the number of files removed.

gc: add dry option and return num removed

---

src/dvc_data/index/diff.py

This will allow us to jump right into the branch of our interest, without messing with entries that we don't care about, thus not having to clean those out later when consuming diff output.
Related https://github.com/iterative/dvc/issues/9507

index: diff: support specifying start key

---

src/dvc_data/index/collect.py
src/dvc_data/index/index.py
tests/index/test_index.py

Related https://github.com/iterative/dvc/issues/9826

index: collect: update dir entry's loaded field after iterating through it

---

src/dvc_data/index/index.py
tests/index/test_storage.py

Related https://github.com/iterative/dvc/pull/9807

index: storage: don't forget to merge storage info

---

src/dvc_data/index/push.py

index: push: handle checkout errors

---

src/dvc_data/index/save.py

The main issue is that we don't use md5 provided by the fs (e.g. dvcfs), which results in needless hash recomputing. We can just use tried-and-tested `hash_file` here for now.
Fixes https://github.com/iterative/dvc/issues/10059

index: md5: use hash_file

---

src/dvc_data/hashfile/db/local.py

Since I am removing progressbar support in https://github.com/iterative/dvc-objects/pull/255, 
I have modified `unprotect` to use callback rather than a progressbar.
However, do note that the callback that we have here is for iterating through files, not for copyfile progress (which now does not exist due to https://github.com/iterative/dvc-objects/pull/255).

localodb.unprotect: use callbacks instead of a progressbar

---

src/dvc_data/hashfile/db/local.py

unprotect: fix pathname in branched callback

---

src/dvc_data/index/build.py

This significantly speeds up entry building on slow filesystems.
Part of https://github.com/iterative/dvc/issues/10059

index: build: use detail=True if not localfs

---

src/dvc_data/index/push.py

Part of https://github.com/iterative/dvc/issues/10185
Pre-requisite for https://github.com/iterative/dvc/pull/10181

index: push: make sure cache files exist

---

src/dvc_data/index/checkout.py
src/dvc_data/index/push.py

Removes `latest_only` since it's only used in a single place, and it feels more like a `diff`/`compare` than `apply`. Also, makes the progress bar logic simpler and avoids nesting of the callbacks (the `apply` gets a callback for `create_files` and creates one internally for `diff`).
Note, this does hardcore `TqdmCallback` explicitly, but we were doing that before in practice already. I have some plans to get rid of this soon by introducing a callback factory for now.
Diff is messed up due to indentation. Use this link for better diff:
https://github.com/iterative/dvc-data/pull/486/files?w=1

apply: remove latest_only, remove nested progress bar

---

src/dvc_data/index/checkout.py

There are three ways to set `factory` in attrs:
1. What is being done in the PR.
```python
@define
class Klass:
attr: list = field(default=Factory(list))
```
2. Using `factory` kwarg, which is a sugar for above.
```python
@define
class Klass:
attr: list = field(factory=list)
```
3. Another sugar for above.
```python
@define
class Klass:
attr: list = Factory(list)
```
1) is verbose, but I prefer 2).

attrs: use sugar syntax for factory

---

src/dvc_data/index/view.py

To be honest, I don't know how to write a test here (there is no test for `iteritems(prefix=)` anyway). So, any help here would be appreciated.
And I haven't been able to re-create that scenario with the test in `dvc-data`, because `DataIndexView.traverse` already filters them out. So my guess is some interaction with `filter_fn` that comes from `dvc`. 
Closes https://github.com/iterative/dvc/issues/10199.

view: run filter_fn over a key

---

src/dvc_data/index/collect.py
src/dvc_data/index/index.py

Related https://github.com/iterative/dvc/issues/10206
`collect` needs tests in general, I will introduce those with `gc` changes in a followup.

index: introduce Storage.read_only

---

src/dvc_data/hashfile/db/__init__.py

- Also changed `__init__` signature to match `ObjectDB`.

hashfiledb: remove unused HashFileDB.config

---

src/dvc_data/index/collect.py

Once we've collected stuff from original indexes, we don't really care about index loading errors and can safely ignore them.

index: collect: ignore loading errors in collected index

---

src/dvc_data/index/fetch.py

Fixes https://github.com/iterative/dvc/issues/9447

index: fetch: don't forget onerror

---

src/dvc_data/index/fetch.py

Ugly hack for local storages. Pretty much only affects local imports in certain cases, which is not super common.
Related https://github.com/iterative/dvc/pull/10270

index: fetch: validate localfs meta using md5

---

src/dvc_data/hashfile/meta.py

Fixes https://github.com/iterative/dvc/issues/10271
from https://github.com/iterative/dvc/issues/10271#issuecomment-1945523951
> When using `BlobClient.get_blob_properties()` the returned etag property is enclosed in `"` quotes. However, when using `BlobContainer.walk_blobs()` the etag property for iterated blobs is not enclosed in quotes. This causes adlfs to have different behavior for the etag field when using `fs.ls(detail=True)` vs `fs.info()`.

hashfile: standardize azure etag format

---

src/dvc_data/fs.py

This PR adds a simple fix for #512, so the cache storage configuration is honoured when pulling remote files into cache.

Honor cache storage when file get pulled into cache

---

src/dvc_data/index/collect.py

related: https://github.com/iterative/dvc/issues/10309
In dvcfs, trying to read `fs.fsid` forces us to load the erepo which may end up raising an SCMError in the event we cannot clone the source repo. In this case, we will not be able to collect anything from that fs, so we should just ignore trying to collect this data/storage

index: skip collection for fs with invalid fsid

---

src/dvc_data/index/collect.py

This might mislead the user to believe it's an error. See
https://github.com/iterative/dvc/issues/10309#issuecomment-2016423953

collect: do not log exc_info

---

src/dvc_data/hashfile/diff.py
src/dvc_data/hashfile/hash_info.py
src/dvc_data/hashfile/meta.py
src/dvc_data/index/diff.py
src/dvc_data/index/index.py

It was added in attrs==22.2.0, and is an alias to `hash`. The `hash` is now deprecated since the latest release 24.1.0.

replace hash with unsafe_hash

---

pyproject.toml
src/dvc_data/compat.py
src/dvc_data/hashfile/build.py
src/dvc_data/hashfile/cache.py
src/dvc_data/hashfile/db/__init__.py
src/dvc_data/hashfile/hash.py
src/dvc_data/hashfile/state.py
src/dvc_data/json_compat.py
tests/hashfile/test_build.py
tests/hashfile/test_cache.py
tests/hashfile/test_state.py

This PR implements batching `save` and `get` in `State`.
As a result of this change, `_build_tree()` is faster by 70% - 90% on the first run, and 50% faster on repeated runs with this PR. You can find the results below for the mnist dataset. 
This should dramatically improve the performance for `dvc add --no-relink`, and other places where we build trees and compute hashes. Real-world impact is mixed and depends on individual commands, but all of the commands show improvements from 4-5 % to 20%, and in some cases,  even 70% or more.
This also brings back support for `core.checksum_jobs` to concurrently hash multiple files at once.
This is done by partitioning the files to hash into two buckets: a) files that are smaller than 1MB and, b) files that are larger than 1MB. 
Files smaller than …

state/cache: implement get_many/set_many

---

src/dvc_data/hashfile/diff.py

Saves about 12 seconds on `dvc add` for an MNIST dataset during checkout.

diff: do not recurse when trying to get stats

---

src/dvc_data/hashfile/checkout.py

For MNIST dataset, this drops total runtime for `dvc add` from 24s to 12s for me.

hashfile/checkout: use save_many to save state

---

src/dvc_data/hashfile/checkout.py
src/dvc_data/hashfile/db/__init__.py
src/dvc_data/hashfile/db/local.py
src/dvc_data/hashfile/db/reference.py
src/dvc_data/hashfile/diff.py
src/dvc_data/hashfile/meta.py
src/dvc_data/hashfile/state.py
tests/hashfile/test_checkout.py
tests/hashfile/test_db.py
tests/hashfile/test_diff.py
tests/hashfile/test_state.py

Requires https://github.com/iterative/dvc/pull/10513 for this to work.

checkout: figure out whether to link or not

---

src/dvc_data/fsutils.py
src/dvc_data/hashfile/build.py
src/dvc_data/hashfile/checkout.py
src/dvc_data/hashfile/db/local.py
src/dvc_data/hashfile/utils.py

Reduces no. of stat calls and avoids _strip_protocol call which is slow when we have large no. of files.
For reducing stat calls upstream, I have a PR in https://github.com/fsspec/filesystem_spec/pull/1659.

speedup localfs.info 

---

src/dvc_data/hashfile/checkout.py
src/dvc_data/index/build.py

For index, use fs.hash_jobs. I am too lazy to go through all APIs and pass this explicitly. This may be a problem for local files in the repo, as they seem to use self.repo.fs which does not load `core.checksum_jobs`.

pass checksum_jobs

---

src/dvc_data/index/diff.py
tests/index/test_diff.py

Fixes iterative/dvc#10515
- I presume the reason for sorting `added` and `deleted` before was to optimize the runtime (more likely to get an early hit in the inner loop). I included this now maintain the former output. In the case of multiple files with the same hash, changing this may result in other pairs being detected as renames. However, if maintaining this is not a priority, I think we can remove it, making it simpler. It will still be deterministic.
- I used asserts for verifying `change.new` and `change.old`, as this seemed to be the convention. LMK. if I should change for exceptions, or if we should just assume `_diff` to always supply valid changes.
- I'm only just aware of the https://github.com/iterative/dvc-bench repo. Should we add a test case to it that would have uncovered …

Performance(diff): faster rename detection

---

src/dvc_data/index/checkout.py
tests/index/test_checkout.py

Fixes [iterative/dvc/#4344](https://github.com/iterative/dvc/issues/4344)

checkout: ensure subdirs are deleted before parent dir
